kind: pipeline
name: test-arm-openjdk8

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: gradle:5.2.1-jdk8
    commands:
      - ./bin/run-ci-tests.sh

---

kind: pipeline
name: test-arm-openjdk11

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: gradle:5.2.1-jdk11
    commands:
      - ./bin/run-ci-tests.sh

---

#kind: pipeline
#name: test-arm-openjdk12
#
#platform:
#  os: linux
#  arch: arm
#
#steps:
#  - name: build
#    image: gradle:5.2.1-jdk12
#    commands:
#      - ./bin/run-ci-tests.sh
#
#---

kind: pipeline
name: test-arm64-openjdk8

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: gradle:5.2.1-jdk8
    commands:
      - ./bin/run-ci-tests.sh

---

kind: pipeline
name: test-arm64-openjdk11

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: gradle:5.2.1-jdk11
    commands:
      - ./bin/run-ci-tests.sh

#---
#
#kind: pipeline
#name: test-arm64-openjdk12
#
#platform:
#  os: linux
#  arch: arm64
#
#steps:
#  - name: build
#    image: gradle:5.2.1-jdk12
#    commands:
#      - ./bin/run-ci-tests.sh
