kind: pipeline
name: test-arm-openjdk8

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: gradle:5.2.1-jdk8
    commands:
      - mkdir -p .gradle .gradle_home
      - gradle --no-daemon --info --full-stacktrace --gradle-user-home "$PWD/.gradle_home" clean test

---

kind: pipeline
name: test-arm-openjdk11

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: gradle:5.2.1-jdk11
    commands:
      - mkdir -p .gradle .gradle_home
      - gradle --no-daemon --info --full-stacktrace --gradle-user-home "$PWD/.gradle_home" clean test

---

#kind: pipeline
#name: test-arm-openjdk12
#
#platform:
#  os: linux
#  arch: arm
#
#steps:
#  - name: build
#    image: gradle:5.2.1-jdk12
#    commands:
#      - mkdir -p .gradle .gradle_home
#      - gradle --no-daemon --info --full-stacktrace --gradle-user-home "$PWD/.gradle_home" clean test
#
#---

kind: pipeline
name: test-arm64-openjdk8

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: gradle:5.2.1-jdk8
    commands:
      - mkdir -p .gradle .gradle_home
      - gradle --no-daemon --info --full-stacktrace --gradle-user-home "$PWD/.gradle_home" clean test

---

kind: pipeline
name: test-arm64-openjdk11

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: gradle:5.2.1-jdk11
    commands:
      - mkdir -p .gradle .gradle_home
      - gradle --no-daemon --info --full-stacktrace --gradle-user-home "$PWD/.gradle_home" clean test

#---
#
#kind: pipeline
#name: test-arm64-openjdk12
#
#platform:
#  os: linux
#  arch: arm64
#
#steps:
#  - name: build
#    image: gradle:5.2.1-jdk12
#    commands:
#      - mkdir -p .gradle .gradle_home
#      - gradle --no-daemon --info --full-stacktrace --gradle-user-home "$PWD/.gradle_home" clean test
