kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: openjdk:8-jdk-stretch
    commands:
      - mkdir ./tmp
      - ./bin/run-ci-tests.sh -Ptest.tmpdir=./tmp

---

kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: openjdk:8-jdk-stretch
    commands:
      - mkdir ./tmp
      - ./bin/run-ci-tests.sh -Ptest.tmpdir=./tmp
