image: openjdk:11

stages:
  - build
  - test
  - test CentOS
  - test Ubuntu
  - test Debian

cache:
  paths:
    - .gradle
    - .gradle_home

build:
  stage: build
  artifacts:
    expire_in: 30 days
    paths:
      - build
  script:
    - mkdir -p .gradle_home
    - ./gradlew --no-daemon --info --full-stacktrace --gradle-user-home "$PWD/.gradle_home" classes testClasses

check-openjdk11:
  stage: test
  needs: ["build"]
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh check

test-centos6-openjdk8:
  stage: test CentOS
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos6-x64:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-centos6-openjdk11:
  stage: test CentOS
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos6-x64:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-centos6-openjdk13:
  stage: test CentOS
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos6-x64:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-centos7-openjdk8:
  stage: test CentOS
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos7:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-centos7-openjdk11:
  stage: test CentOS
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos7:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-centos7-openjdk13:
  stage: test CentOS
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-centos7:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-ubuntu16.04-openjdk8:
  stage: test Ubuntu
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu16.04:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-ubuntu16.04-openjdk11:
  stage: test Ubuntu
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu16.04:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-ubuntu16.04-openjdk13:
  stage: test Ubuntu
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu16.04:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-ubuntu18.04-openjdk8:
  stage: test Ubuntu
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu18.04:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-ubuntu18.04-openjdk11:
  stage: test Ubuntu
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu18.04:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-ubuntu18.04-openjdk13:
  stage: test Ubuntu
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-ubuntu18.04:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-debian-stretch-openjdk8:
  stage: test Debian
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-stretch:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-debian-stretch-openjdk11:
  stage: test Debian
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-stretch:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-debian-stretch-openjdk13:
  stage: test Debian
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-stretch:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-debian-buster-openjdk8:
  stage: test Debian
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-buster:openjdk8
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-debian-buster-openjdk11:
  stage: test Debian
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-buster:openjdk11
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh

test-debian-buster-openjdk13:
  stage: test Debian
  needs: ["build"]
  image: registry.gitlab.com/jsass/docker/test-debian-buster:openjdk13
  dependencies:
    - build
  script:
    - ./bin/run-ci-tests.sh
