language: shell

sudo: required

git:
  submodules: false

matrix:
  include:
    - os: osx
    - os: windows

before_install:
  - ./.travis_before_install.sh

install: true

script:
  - ./.travis_script.sh
