language: java

sudo: required

git:
  submodules: false

matrix:
  include:
    - os: linux
      jdk: openjdk8
      sudo: required
      services:
        - docker
    - os: osx

before_install:
  - ./.travis_before_install.sh

install: true

script:
  - ./.travis_script.sh

after_script:
  - ./.travis_after_script.sh
